### ISSUE TITLE
Nav Bar Spacing

### ISSUE THREAD

**Issue by rahulssheth1** [Bruin-Entrepreneurs/startup_fair_2018_final#3]
* StartupFairLA Title should be on the left 
* Logo should show up in navbar

**Comment by bovem** [comment]
I would like to work on this

**Comment by bovem** [comment]
![screenshot from 2018-08-27 14-39-51](https://user-images.githubusercontent.com/29746858/44651522-48f04900-aa07-11e8-91eb-7d452b69e617.png)
This is what I have made
